#!/bin/bash

# Example script to merge the two example DLCs

EXAMPLE_DIR="example_dlcs"
DLC1="$EXAMPLE_DIR/0dd32d-T72B3M_Arena/t72b3m/dlc.rpf"
DLC2="$EXAMPLE_DIR/31dc8a-M113A1/m113a1/dlc.rpf"
OUTPUT="merged_vehicles.rpf"

echo "Merging example DLC files..."
echo "============================"
echo ""
echo "NEW: Enhanced merger with debugging features!"
echo ""
echo "Method 1: Merge specific files"
echo "Input files:"
echo "  1. $DLC1"
echo "  2. $DLC2"
echo ""
echo "Method 2: Merge entire directory (recommended)"
echo "Input directory: $EXAMPLE_DIR"
echo ""
echo "Output file: $OUTPUT"
echo ""
echo "=== RECOMMENDED COMMANDS ==="
echo ""
echo "1. Dry run with structure analysis:"
echo "./bin/Debug/net8.0/DLCMerger -i \"$EXAMPLE_DIR\" -o \"$OUTPUT\" -v -d -s"
echo ""
echo "2. Full merge with debugging:"
echo "./bin/Debug/net8.0/DLCMerger -i \"$EXAMPLE_DIR\" -o \"$OUTPUT\" -v -s -f"
echo ""
echo "3. Individual file merge:"
echo "./bin/Debug/net8.0/DLCMerger -i \"$DLC1\" -i \"$DLC2\" -o \"$OUTPUT\" -v -s -f"
echo ""
echo "=== NEW FLAGS ==="
echo "-s, --show-structure  Show detailed RPF structure trees"
echo "-v, --verbose        Show detailed processing information"
echo "-d, --dry-run        Test merge without creating output"
echo "-f, --force          Overwrite existing output file"